//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account List.
        /// </summary>
        public static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more emails.
        /// </summary>
        public static string AddMoreEmails {
            get {
                return ResourceManager.GetString("AddMoreEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more phones.
        /// </summary>
        public static string AddMorePhones {
            get {
                return ResourceManager.GetString("AddMorePhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist..
        /// </summary>
        public static string AlreadyExistMsg {
            get {
                return ResourceManager.GetString("AlreadyExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARPE Description.
        /// </summary>
        public static string ARPEDescription {
            get {
                return ResourceManager.GetString("ARPEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment / File.
        /// </summary>
        public static string AttachmentFile {
            get {
                return ResourceManager.GetString("AttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Code.
        /// </summary>
        public static string BusinessCode {
            get {
                return ResourceManager.GetString("BusinessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Description.
        /// </summary>
        public static string BusinessDescription {
            get {
                return ResourceManager.GetString("BusinessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        public static string BusinessType {
            get {
                return ResourceManager.GetString("BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Last Name.
        /// </summary>
        public static string ContactLastName {
            get {
                return ResourceManager.GetString("ContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Position.
        /// </summary>
        public static string ContactPosition {
            get {
                return ResourceManager.GetString("ContactPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit History Detail.
        /// </summary>
        public static string CreditHistoryDetail {
            get {
                return ResourceManager.GetString("CreditHistoryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit amount added successfully. .
        /// </summary>
        public static string CreditHistorySuccessMsg {
            get {
                return ResourceManager.GetString("CreditHistorySuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Known As.
        /// </summary>
        public static string DBAName {
            get {
                return ResourceManager.GetString("DBAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit History Paid.
        /// </summary>
        public static string DebitHistoryPaid {
            get {
                return ResourceManager.GetString("DebitHistoryPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit amount added successfully. .
        /// </summary>
        public static string DebitHistorySuccessMsg {
            get {
                return ResourceManager.GetString("DebitHistorySuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete or fill address detail..
        /// </summary>
        public static string DeleteOrFillAddressDetailMsg {
            get {
                return ResourceManager.GetString("DeleteOrFillAddressDetailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete or fill contact detail..
        /// </summary>
        public static string DeleteOrFillContactDetailMsg {
            get {
                return ResourceManager.GetString("DeleteOrFillContactDetailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with same registration information already exist..
        /// </summary>
        public static string DuplicateRegistrationInfo {
            get {
                return ResourceManager.GetString("DuplicateRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        public static string EditAddress {
            get {
                return ResourceManager.GetString("EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Email.
        /// </summary>
        public static string EditEmail {
            get {
                return ResourceManager.GetString("EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Phone.
        /// </summary>
        public static string EditPhone {
            get {
                return ResourceManager.GetString("EditPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Identification Number.
        /// </summary>
        public static string EIN {
            get {
                return ResourceManager.GetString("EIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Type.
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempt From IVA.
        /// </summary>
        public static string ExemptFromIVA {
            get {
                return ResourceManager.GetString("ExemptFromIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Template.
        /// </summary>
        public static string FinanceTemplate {
            get {
                return ResourceManager.GetString("FinanceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifica.
        /// </summary>
        public static string Identifica {
            get {
                return ResourceManager.GetString("Identifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string IDType {
            get {
                return ResourceManager.GetString("IDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur in Account Import.
        /// </summary>
        public static string ImportAccountFailedMsg {
            get {
                return ResourceManager.GetString("ImportAccountFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account Number.
        /// </summary>
        public static string InvalidAccountNumber {
            get {
                return ResourceManager.GetString("InvalidAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Sponsor.
        /// </summary>
        public static string IsSponsor {
            get {
                return ResourceManager.GetString("IsSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Sub-Account.
        /// </summary>
        public static string IsSubAccount {
            get {
                return ResourceManager.GetString("IsSubAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Credit History.
        /// </summary>
        public static string ListCreditHistory {
            get {
                return ResourceManager.GetString("ListCreditHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Debit History.
        /// </summary>
        public static string ListDebitHistory {
            get {
                return ResourceManager.GetString("ListDebitHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAICS Code.
        /// </summary>
        public static string NAICSCode {
            get {
                return ResourceManager.GetString("NAICSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address.
        /// </summary>
        public static string NewAddress {
            get {
                return ResourceManager.GetString("NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Attachment / File.
        /// </summary>
        public static string NewAttachmentFile {
            get {
                return ResourceManager.GetString("NewAttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Business.
        /// </summary>
        public static string NewBusiness {
            get {
                return ResourceManager.GetString("NewBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Business.
        /// </summary>
        public static string NewBusinessAccount {
            get {
                return ResourceManager.GetString("NewBusinessAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        public static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Citizen.
        /// </summary>
        public static string NewIndividualAccount {
            get {
                return ResourceManager.GetString("NewIndividualAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Phone.
        /// </summary>
        public static string NewPhone {
            get {
                return ResourceManager.GetString("NewPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string NewTitle {
            get {
                return ResourceManager.GetString("NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address Line 1.
        /// </summary>
        public static string OfficeAddressLine1 {
            get {
                return ResourceManager.GetString("OfficeAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address Line 2.
        /// </summary>
        public static string OfficeAddressLine2 {
            get {
                return ResourceManager.GetString("OfficeAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office City.
        /// </summary>
        public static string OfficeCity {
            get {
                return ResourceManager.GetString("OfficeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Country.
        /// </summary>
        public static string OfficeCountry {
            get {
                return ResourceManager.GetString("OfficeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office State.
        /// </summary>
        public static string OfficeState {
            get {
                return ResourceManager.GetString("OfficeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Town.
        /// </summary>
        public static string OfficeTown {
            get {
                return ResourceManager.GetString("OfficeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Zip Code.
        /// </summary>
        public static string OfficeZipCode {
            get {
                return ResourceManager.GetString("OfficeZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGPe Description.
        /// </summary>
        public static string OGPEDescription {
            get {
                return ResourceManager.GetString("OGPEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Email.
        /// </summary>
        public static string OtherEmail {
            get {
                return ResourceManager.GetString("OtherEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Phone.
        /// </summary>
        public static string OtherPhone {
            get {
                return ResourceManager.GetString("OtherPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Type.
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address Line 1.
        /// </summary>
        public static string PostalAddressLine1 {
            get {
                return ResourceManager.GetString("PostalAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address Line 2.
        /// </summary>
        public static string PostalAddressLine2 {
            get {
                return ResourceManager.GetString("PostalAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal City.
        /// </summary>
        public static string PostalCity {
            get {
                return ResourceManager.GetString("PostalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Country.
        /// </summary>
        public static string PostalCountry {
            get {
                return ResourceManager.GetString("PostalCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal State.
        /// </summary>
        public static string PostalState {
            get {
                return ResourceManager.GetString("PostalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Town.
        /// </summary>
        public static string PostalTown {
            get {
                return ResourceManager.GetString("PostalTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Zip Code.
        /// </summary>
        public static string PostalZipCode {
            get {
                return ResourceManager.GetString("PostalZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Email.
        /// </summary>
        public static string PrimaryEmail {
            get {
                return ResourceManager.GetString("PrimaryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Phone.
        /// </summary>
        public static string PrimaryPhone {
            get {
                return ResourceManager.GetString("PrimaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceID.
        /// </summary>
        public static string ReferenceID {
            get {
                return ResourceManager.GetString("ReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Number.
        /// </summary>
        public static string RegisterNumber {
            get {
                return ResourceManager.GetString("RegisterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one address is required..
        /// </summary>
        public static string RequiredValidationAddressMsg {
            get {
                return ResourceManager.GetString("RequiredValidationAddressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one contact is required..
        /// </summary>
        public static string RequiredValidationContactMsg {
            get {
                return ResourceManager.GetString("RequiredValidationContactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string Salutation {
            get {
                return ResourceManager.GetString("Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Last Name.
        /// </summary>
        public static string SecondLastName {
            get {
                return ResourceManager.GetString("SecondLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Department Register Number.
        /// </summary>
        public static string StateDepartmentRegisterNumber {
            get {
                return ResourceManager.GetString("StateDepartmentRegisterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Dept. Register No..
        /// </summary>
        public static string StateDepartmentRegisterNumber1 {
            get {
                return ResourceManager.GetString("StateDepartmentRegisterNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury Department.
        /// </summary>
        public static string TreasuryDepartment {
            get {
                return ResourceManager.GetString("TreasuryDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has one or more grant. You can not deactivate account..
        /// </summary>
        public static string ValidateForInactiveAccount {
            get {
                return ResourceManager.GetString("ValidateForInactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has one or more grant. You can not remove a sponsor..
        /// </summary>
        public static string ValidateForInactiveSponsor {
            get {
                return ResourceManager.GetString("ValidateForInactiveSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid number..
        /// </summary>
        public static string ValSSEINNumber {
            get {
                return ResourceManager.GetString("ValSSEINNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Address.
        /// </summary>
        public static string ViewAddress {
            get {
                return ResourceManager.GetString("ViewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contact.
        /// </summary>
        public static string ViewContact {
            get {
                return ResourceManager.GetString("ViewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Email.
        /// </summary>
        public static string ViewEmail {
            get {
                return ResourceManager.GetString("ViewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Phone.
        /// </summary>
        public static string ViewPhone {
            get {
                return ResourceManager.GetString("ViewPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Account.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        public static string WorkPhone {
            get {
                return ResourceManager.GetString("WorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
