//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.AccountService", typeof(AccountService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Measure.
        /// </summary>
        public static string ActualMeasure {
            get {
                return ResourceManager.GetString("ActualMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual measure should be greater than zero..
        /// </summary>
        public static string ActualMeasureRequiredMessage {
            get {
                return ResourceManager.GetString("ActualMeasureRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Additional Information.
        /// </summary>
        public static string AdditionalInformationTitle {
            get {
                return ResourceManager.GetString("AdditionalInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note saved successfully..
        /// </summary>
        public static string AddNoteSuccessMessage {
            get {
                return ResourceManager.GetString("AddNoteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Amount.
        /// </summary>
        public static string AdjustmentAmount {
            get {
                return ResourceManager.GetString("AdjustmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment deleted successfully..
        /// </summary>
        public static string AdjustmentDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("AdjustmentDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Reason.
        /// </summary>
        public static string AdjustmentReason {
            get {
                return ResourceManager.GetString("AdjustmentReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments.
        /// </summary>
        public static string Adjustments {
            get {
                return ResourceManager.GetString("Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment applied successfully..
        /// </summary>
        public static string AdjustmentSuccessMsg {
            get {
                return ResourceManager.GetString("AdjustmentSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Year.
        /// </summary>
        public static string AllYear {
            get {
                return ResourceManager.GetString("AllYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid Against Invoice.
        /// </summary>
        public static string AmountPaidAgainstInvoice {
            get {
                return ResourceManager.GetString("AmountPaidAgainstInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To Pay.
        /// </summary>
        public static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Income.
        /// </summary>
        public static string AnnualIncome {
            get {
                return ResourceManager.GetString("AnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To.
        /// </summary>
        public static string ApplyTo {
            get {
                return ResourceManager.GetString("ApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineal Meters  (&lt;em&gt;m&lt;/em&gt; &lt;sup&gt;2&lt;/sup&gt;).
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of Period.
        /// </summary>
        public static string AsOfPeriod {
            get {
                return ResourceManager.GetString("AsOfPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one file is required for validate measured water filing..
        /// </summary>
        public static string AtleastOneFileRequiredForValidateMeasuredWaterMsg {
            get {
                return ResourceManager.GetString("AtleastOneFileRequiredForValidateMeasuredWaterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigom.
        /// </summary>
        public static string Codigom {
            get {
                return ResourceManager.GetString("Codigom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the {0}?.
        /// </summary>
        public static string ConfirmationMsgForCustomFieldUpdate {
            get {
                return ResourceManager.GetString("ConfirmationMsgForCustomFieldUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction applied successfully.
        /// </summary>
        public static string CorrectionSuccessMsg {
            get {
                return ResourceManager.GetString("CorrectionSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Per Every Colones Million Declarated In Property.
        /// </summary>
        public static string CostPerEveryColonesMillionDeclaratedInProperty {
            get {
                return ResourceManager.GetString("CostPerEveryColonesMillionDeclaratedInProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount Applied.
        /// </summary>
        public static string CreditApplied {
            get {
                return ResourceManager.GetString("CreditApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount Balance.
        /// </summary>
        public static string CreditBalance {
            get {
                return ResourceManager.GetString("CreditBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit for Sale of Property.
        /// </summary>
        public static string CreditSaleProperty {
            get {
                return ResourceManager.GetString("CreditSaleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit for Uncollectible Accounts.
        /// </summary>
        public static string CreditUncollectibleAccounts {
            get {
                return ResourceManager.GetString("CreditUncollectibleAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Reading.
        /// </summary>
        public static string CurrentReading {
            get {
                return ResourceManager.GetString("CurrentReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field.
        /// </summary>
        public static string CustomField1 {
            get {
                return ResourceManager.GetString("CustomField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account service deleted successfully..
        /// </summary>
        public static string DeleteAccountServiceSuccMsg {
            get {
                return ResourceManager.GetString("DeleteAccountServiceSuccMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to eliminate this adjustment.
        /// </summary>
        public static string DeleteAdjustment {
            get {
                return ResourceManager.GetString("DeleteAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to eliminate this all exemption which does not have any payment.
        /// </summary>
        public static string DeleteAllExemption {
            get {
                return ResourceManager.GetString("DeleteAllExemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this filling.
        /// </summary>
        public static string DeleteConfirmFillingMsg {
            get {
                return ResourceManager.GetString("DeleteConfirmFillingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to eliminate this exoneration.
        /// </summary>
        public static string DeleteExemption {
            get {
                return ResourceManager.GetString("DeleteExemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing deleted successfully..
        /// </summary>
        public static string DeleteFillingSuccessMsg {
            get {
                return ResourceManager.GetString("DeleteFillingSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Description.
        /// </summary>
        public static string DiscountDescription {
            get {
                return ResourceManager.GetString("DiscountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by paying your debt by.
        /// </summary>
        public static string DiscountMessageEnd {
            get {
                return ResourceManager.GetString("DiscountMessageEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avail discount of.
        /// </summary>
        public static string DiscountMessageStart {
            get {
                return ResourceManager.GetString("DiscountMessageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Rate %.
        /// </summary>
        public static string DiscountRate {
            get {
                return ResourceManager.GetString("DiscountRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exemption.
        /// </summary>
        public static string EditExemption {
            get {
                return ResourceManager.GetString("EditExemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filing for.
        /// </summary>
        public static string EditFilingForTitle {
            get {
                return ResourceManager.GetString("EditFilingForTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit License Number.
        /// </summary>
        public static string EditLicenseNumber {
            get {
                return ResourceManager.GetString("EditLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Value of.
        /// </summary>
        public static string EditValueOf {
            get {
                return ResourceManager.GetString("EditValueOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption (%).
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempt Admissions.
        /// </summary>
        public static string ExemptAdmissions {
            get {
                return ResourceManager.GetString("ExemptAdmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Tangible Furniture Exempt.
        /// </summary>
        public static string ExemptFurnitureSale {
            get {
                return ResourceManager.GetString("ExemptFurnitureSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption.
        /// </summary>
        public static string Exemption {
            get {
                return ResourceManager.GetString("Exemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption Amount.
        /// </summary>
        public static string ExemptionAmount {
            get {
                return ResourceManager.GetString("ExemptionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption deleted successfully..
        /// </summary>
        public static string ExemptionDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("ExemptionDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption Period.
        /// </summary>
        public static string ExemptionPeriod {
            get {
                return ResourceManager.GetString("ExemptionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption Reason.
        /// </summary>
        public static string ExemptionReason {
            get {
                return ResourceManager.GetString("ExemptionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption applied successfully..
        /// </summary>
        public static string ExemptionSuccessMsg {
            get {
                return ResourceManager.GetString("ExemptionSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less - Exempt Returns.
        /// </summary>
        public static string ExemptReturns {
            get {
                return ResourceManager.GetString("ExemptReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale of Exempt Services.
        /// </summary>
        public static string ExemptServicesSale {
            get {
                return ResourceManager.GetString("ExemptServicesSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Measure Water.
        /// </summary>
        public static string ExportMeasureWater {
            get {
                return ResourceManager.GetString("ExportMeasureWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your extension due date is {0}.
        /// </summary>
        public static string ExtensionInfoMsg {
            get {
                return ResourceManager.GetString("ExtensionInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Sales.
        /// </summary>
        public static string ExtraSales {
            get {
                return ResourceManager.GetString("ExtraSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing Amount.
        /// </summary>
        public static string FilingAmount {
            get {
                return ResourceManager.GetString("FilingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing Period.
        /// </summary>
        public static string FilingPeriod {
            get {
                return ResourceManager.GetString("FilingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing.
        /// </summary>
        public static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...&lt;br /&gt;We are working on filing process..
        /// </summary>
        public static string FillingProcessInfoMsg {
            get {
                return ResourceManager.GetString("FillingProcessInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinalStep {
            get {
                return ResourceManager.GetString("FinalStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not exist in finance. Contact your administrator..
        /// </summary>
        public static string FinanceItemNotExistMsg {
            get {
                return ResourceManager.GetString("FinanceItemNotExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix File.
        /// </summary>
        public static string FixFile {
            get {
                return ResourceManager.GetString("FixFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form IVU - Treasury.
        /// </summary>
        public static string FormIVUTreasury {
            get {
                return ResourceManager.GetString("FormIVUTreasury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go to Finance for payment..
        /// </summary>
        public static string GoToFinanceForPaymentMsg {
            get {
                return ResourceManager.GetString("GoToFinanceForPaymentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Amount should be greater than zero..
        /// </summary>
        public static string GrossAmountRequiredMessage {
            get {
                return ResourceManager.GetString("GrossAmountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Volume Amount.
        /// </summary>
        public static string GrossVolumeAmount {
            get {
                return ResourceManager.GetString("GrossVolumeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Consumption.
        /// </summary>
        public static string HighConsumption {
            get {
                return ResourceManager.GetString("HighConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Number / Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification does not exists..
        /// </summary>
        public static string Identificationdoesnotexists_ {
            get {
                return ResourceManager.GetString("Identificationdoesnotexists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur in measured water filing Import..
        /// </summary>
        public static string ImportMeasuredWaterFailedMsg {
            get {
                return ResourceManager.GetString("ImportMeasuredWaterFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Measured Water Filing.
        /// </summary>
        public static string ImportMeasuredWaterFiling {
            get {
                return ResourceManager.GetString("ImportMeasuredWaterFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...\n We are working on import measured water filing process..
        /// </summary>
        public static string ImportMeasuredWaterFillingProcessInfoMsg {
            get {
                return ResourceManager.GetString("ImportMeasuredWaterFillingProcessInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports for Use.
        /// </summary>
        public static string ImportsUse {
            get {
                return ResourceManager.GetString("ImportsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistencies.
        /// </summary>
        public static string Inconsistencies {
            get {
                return ResourceManager.GetString("Inconsistencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account Service.
        /// </summary>
        public static string InvalidAccountService {
            get {
                return ResourceManager.GetString("InvalidAccountService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid License Number.
        /// </summary>
        public static string InvalidLicenseNumber {
            get {
                return ResourceManager.GetString("InvalidLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invoice has been generated..
        /// </summary>
        public static string InvoiceGeneratedMsg {
            get {
                return ResourceManager.GetString("InvoiceGeneratedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account service issued successfully..
        /// </summary>
        public static string IssueSuccessMsg {
            get {
                return ResourceManager.GetString("IssueSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Total.
        /// </summary>
        public static string ItemTotal {
            get {
                return ResourceManager.GetString("ItemTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Reading.
        /// </summary>
        public static string LastReading {
            get {
                return ResourceManager.GetString("LastReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should be greater than zero..
        /// </summary>
        public static string LengthRequiredMessage {
            get {
                return ResourceManager.GetString("LengthRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License ID.
        /// </summary>
        public static string LicenseID {
            get {
                return ResourceManager.GetString("LicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number already exists..
        /// </summary>
        public static string LicenseNumberAlreadyExistsMsg {
            get {
                return ResourceManager.GetString("LicenseNumberAlreadyExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number updated successfully..
        /// </summary>
        public static string LicenseNumberUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("LicenseNumberUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string LicenseType {
            get {
                return ResourceManager.GetString("LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineal Meters.
        /// </summary>
        public static string LinealMeters {
            get {
                return ResourceManager.GetString("LinealMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Receivable (%).
        /// </summary>
        public static string LiquorPercentage {
            get {
                return ResourceManager.GetString("LiquorPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Services.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string LockReason {
            get {
                return ResourceManager.GetString("LockReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Service.
        /// </summary>
        public static string LockService {
            get {
                return ResourceManager.GetString("LockService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account service is locked successfully..
        /// </summary>
        public static string LockSuccessMsg {
            get {
                return ResourceManager.GetString("LockSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Payment.
        /// </summary>
        public static string MakePayment {
            get {
                return ResourceManager.GetString("MakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Type.
        /// </summary>
        public static string MovementType {
            get {
                return ResourceManager.GetString("MovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Adjustment.
        /// </summary>
        public static string NewAdjustment {
            get {
                return ResourceManager.GetString("NewAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Exemption.
        /// </summary>
        public static string NewExemption {
            get {
                return ResourceManager.GetString("NewExemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New License.
        /// </summary>
        public static string NewLicense {
            get {
                return ResourceManager.GetString("NewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sales Tax Return.
        /// </summary>
        public static string NewSalesTaxReturn {
            get {
                return ResourceManager.GetString("NewSalesTaxReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service.
        /// </summary>
        public static string NewService {
            get {
                return ResourceManager.GetString("NewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Service.
        /// </summary>
        public static string NewTitle {
            get {
                return ResourceManager.GetString("NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no service configured in selected service type..
        /// </summary>
        public static string NoServiceConfiguredMsg {
            get {
                return ResourceManager.GetString("NoServiceConfiguredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes By.
        /// </summary>
        public static string NotesBy {
            get {
                return ResourceManager.GetString("NotesBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Off Amount.
        /// </summary>
        public static string PaidOffAmount {
            get {
                return ResourceManager.GetString("PaidOffAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment History.
        /// </summary>
        public static string PaymentHistory {
            get {
                return ResourceManager.GetString("PaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PaymentHistoryDate {
            get {
                return ResourceManager.GetString("PaymentHistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for Invoice No. #INVOICEID# is pending..
        /// </summary>
        public static string PaymentPendingMsg {
            get {
                return ResourceManager.GetString("PaymentPendingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait...&lt;br /&gt;We are working on payment process..
        /// </summary>
        public static string PaymentProcessInfoMsg {
            get {
                return ResourceManager.GetString("PaymentProcessInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string PaymentTotal {
            get {
                return ResourceManager.GetString("PaymentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        public static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Description.
        /// </summary>
        public static string PenaltyDescription {
            get {
                return ResourceManager.GetString("PenaltyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Period.
        /// </summary>
        public static string PendingPeriod {
            get {
                return ResourceManager.GetString("PendingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period doesn&apos;t match with selected period..
        /// </summary>
        public static string PeriodNotMatchWithSelectedPeriod {
            get {
                return ResourceManager.GetString("PeriodNotMatchWithSelectedPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than 12 characters..
        /// </summary>
        public static string PleaseEnterNoMoreThan12CharactersMsg {
            get {
                return ResourceManager.GetString("PleaseEnterNoMoreThan12CharactersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the Service Group you want to add to Account..
        /// </summary>
        public static string PleaseSelectServiceGroup {
            get {
                return ResourceManager.GetString("PleaseSelectServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the Service Type you want to add to Account..
        /// </summary>
        public static string PleaseSelectServiceType {
            get {
                return ResourceManager.GetString("PleaseSelectServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filing for.
        /// </summary>
        public static string PopupFillingTitle {
            get {
                return ResourceManager.GetString("PopupFillingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Measure.
        /// </summary>
        public static string PreviousMeasure {
            get {
                return ResourceManager.GetString("PreviousMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous measure should be greater than zero..
        /// </summary>
        public static string PreviousMeasureRequiredMessage {
            get {
                return ResourceManager.GetString("PreviousMeasureRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal per Period.
        /// </summary>
        public static string PrincipalForPeriod {
            get {
                return ResourceManager.GetString("PrincipalForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Account Service.
        /// </summary>
        public static string PrintAccountService {
            get {
                return ResourceManager.GetString("PrintAccountService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio Autónomo de Caguas.
        /// </summary>
        public static string PrintPopupSubTitle {
            get {
                return ResourceManager.GetString("PrintPopupSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Libre Asociado de Puerto Rico.
        /// </summary>
        public static string PrintPopupTitle {
            get {
                return ResourceManager.GetString("PrintPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License printed successfully..
        /// </summary>
        public static string PrintSuccessMsg {
            get {
                return ResourceManager.GetString("PrintSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases and Imports for Resale.
        /// </summary>
        public static string PurchasesImportsResale {
            get {
                return ResourceManager.GetString("PurchasesImportsResale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase subject to IVU.
        /// </summary>
        public static string PurchaseSubjectToTax {
            get {
                return ResourceManager.GetString("PurchaseSubjectToTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License re-printed successfully..
        /// </summary>
        public static string RePrintSuccessMsg {
            get {
                return ResourceManager.GetString("RePrintSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must not be greater than gross amount..
        /// </summary>
        public static string RequiredFillingMaxValueErrMsg {
            get {
                return ResourceManager.GetString("RequiredFillingMaxValueErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total must be at least 1..
        /// </summary>
        public static string RequiredTotalValueErrMsg {
            get {
                return ResourceManager.GetString("RequiredTotalValueErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Amount.
        /// </summary>
        public static string ReturnAmount {
            get {
                return ResourceManager.GetString("ReturnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineal Meters (&lt;em&gt;m&lt;/em&gt;).
        /// </summary>
        public static string RoadsCleaningLinealMeters {
            get {
                return ResourceManager.GetString("RoadsCleaningLinealMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segrega.
        /// </summary>
        public static string Segrega {
            get {
                return ResourceManager.GetString("Segrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester 1 Principal.
        /// </summary>
        public static string Semester1Principal {
            get {
                return ResourceManager.GetString("Semester1Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester 2 Principal.
        /// </summary>
        public static string Semester2Principal {
            get {
                return ResourceManager.GetString("Semester2Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Additional Information.
        /// </summary>
        public static string ServiceAdditionalInformation {
            get {
                return ResourceManager.GetString("ServiceAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Service Group.
        /// </summary>
        public static string ServiceGroupTitle {
            get {
                return ResourceManager.GetString("ServiceGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID.
        /// </summary>
        public static string ServiceID {
            get {
                return ResourceManager.GetString("ServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Periods.
        /// </summary>
        public static string ServicePeriodList {
            get {
                return ResourceManager.GetString("ServicePeriodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Service.
        /// </summary>
        public static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Service Type.
        /// </summary>
        public static string ServiceTypeTitle {
            get {
                return ResourceManager.GetString("ServiceTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area (&lt;em&gt;m&lt;/em&gt; &lt;sup&gt;2&lt;/sup&gt;).
        /// </summary>
        public static string SideWalksArea {
            get {
                return ResourceManager.GetString("SideWalksArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension Order.
        /// </summary>
        public static string SuspensionOrder {
            get {
                return ResourceManager.GetString("SuspensionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System has found previous water reading data, processed on.
        /// </summary>
        public static string SystemFoundPreviousWaterReading {
            get {
                return ResourceManager.GetString("SystemFoundPreviousWaterReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable Admissions.
        /// </summary>
        public static string TaxableAdmissions {
            get {
                return ResourceManager.GetString("TaxableAdmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tributable Tangible Furniture Sale.
        /// </summary>
        public static string TaxableFurnitureSale {
            get {
                return ResourceManager.GetString("TaxableFurnitureSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less - Taxable Items Returns.
        /// </summary>
        public static string TaxableItemsReturns {
            get {
                return ResourceManager.GetString("TaxableItemsReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable Sales.
        /// </summary>
        public static string TaxableSales {
            get {
                return ResourceManager.GetString("TaxableSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale of Taxable Services.
        /// </summary>
        public static string TaxableServicesSale {
            get {
                return ResourceManager.GetString("TaxableServicesSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Credit Paid.
        /// </summary>
        public static string TaxCreditPaid {
            get {
                return ResourceManager.GetString("TaxCreditPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Period Only.
        /// </summary>
        public static string ThisPeriod {
            get {
                return ResourceManager.GetString("ThisPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Extra Sales.
        /// </summary>
        public static string TotalExemptSales {
            get {
                return ResourceManager.GetString("TotalExemptSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Subject To IVU.
        /// </summary>
        public static string TotalSubjectToIVU {
            get {
                return ResourceManager.GetString("TotalSubjectToIVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Taxable Sales.
        /// </summary>
        public static string TotalTaxableSales {
            get {
                return ResourceManager.GetString("TotalTaxableSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Use Subject to the IVU.
        /// </summary>
        public static string TotalUseSubjectIVU {
            get {
                return ResourceManager.GetString("TotalUseSubjectIVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred this year. View Notes.
        /// </summary>
        public static string TransferNoteText {
            get {
                return ResourceManager.GetString("TransferNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost per Meter.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCostMulta {
            get {
                return ResourceManager.GetString("UnitCostMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost per Square Meter.
        /// </summary>
        public static string UnitCostPerSquareMeter {
            get {
                return ResourceManager.GetString("UnitCostPerSquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account service is unlocked successfully..
        /// </summary>
        public static string UnlockSuccessMsg {
            get {
                return ResourceManager.GetString("UnlockSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Previous Data will be delete.
        /// </summary>
        public static string UpdateWaringMsg {
            get {
                return ResourceManager.GetString("UpdateWaringMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-consumption and Use of Inventory.
        /// </summary>
        public static string UseofInventory {
            get {
                return ResourceManager.GetString("UseofInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should not exceed amount due..
        /// </summary>
        public static string ValAmountToPay {
            get {
                return ResourceManager.GetString("ValAmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Measured Water Filing.
        /// </summary>
        public static string ValidateMeasuredWaterFiling {
            get {
                return ResourceManager.GetString("ValidateMeasuredWaterFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...\n We are working on validate measured water filing process..
        /// </summary>
        public static string ValidateMeasuredWaterFillingProcessInfoMsg {
            get {
                return ResourceManager.GetString("ValidateMeasuredWaterFillingProcessInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists a filing for same service and month..
        /// </summary>
        public static string ValidationAlreadyExistFillingForSameServiceAndMonth {
            get {
                return ResourceManager.GetString("ValidationAlreadyExistFillingForSameServiceAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category does not exist..
        /// </summary>
        public static string ValidationCategoryNotExist {
            get {
                return ResourceManager.GetString("ValidationCategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be empty..
        /// </summary>
        public static string ValidationCategoryRequired {
            get {
                return ResourceManager.GetString("ValidationCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigom cannot be empty..
        /// </summary>
        public static string ValidationCodigomRequired {
            get {
                return ResourceManager.GetString("ValidationCodigomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current reading must be greater than last reading..
        /// </summary>
        public static string ValidationCurrentReadingMustBeGreaterThanLastReading {
            get {
                return ResourceManager.GetString("ValidationCurrentReadingMustBeGreaterThanLastReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Reading is 0..
        /// </summary>
        public static string ValidationCurrentReadingZero {
            get {
                return ResourceManager.GetString("ValidationCurrentReadingZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be empty..
        /// </summary>
        public static string ValidationDateRequired {
            get {
                return ResourceManager.GetString("ValidationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string ValidationInvalidDate {
            get {
                return ResourceManager.GetString("ValidationInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of Date is invalid.Provide in DDMMYYYY format..
        /// </summary>
        public static string ValidationInvalidDateFormat {
            get {
                return ResourceManager.GetString("ValidationInvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Length.
        /// </summary>
        public static string ValidationInvalidDateLength {
            get {
                return ResourceManager.GetString("ValidationInvalidDateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period is less than Service Start Period..
        /// </summary>
        public static string ValidationPeriodLessThanServiceStartPeriod {
            get {
                return ResourceManager.GetString("ValidationPeriodLessThanServiceStartPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading cannot be empty..
        /// </summary>
        public static string ValidationReadingRequired {
            get {
                return ResourceManager.GetString("ValidationReadingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is inactive..
        /// </summary>
        public static string ValidationServiceInactive {
            get {
                return ResourceManager.GetString("ValidationServiceInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is locked..
        /// </summary>
        public static string ValidationServiceLocked {
            get {
                return ResourceManager.GetString("ValidationServiceLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not available for this year..
        /// </summary>
        public static string ValidationServiceNotAvailableForThisYear {
            get {
                return ResourceManager.GetString("ValidationServiceNotAvailableForThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicacion Or Codigom does not belong to the account record..
        /// </summary>
        public static string ValidationUbicacionOrCodigomNotBelongToAccount {
            get {
                return ResourceManager.GetString("ValidationUbicacionOrCodigomNotBelongToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicacion cannot be empty..
        /// </summary>
        public static string ValidationUbicacionRequired {
            get {
                return ResourceManager.GetString("ValidationUbicacionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water consumption is grater then 100..
        /// </summary>
        public static string ValidationWaterConsumprionGreaterThanZero {
            get {
                return ResourceManager.GetString("ValidationWaterConsumprionGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Filing for.
        /// </summary>
        public static string ViewFilingForTitle {
            get {
                return ResourceManager.GetString("ViewFilingForTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Suspension Order.
        /// </summary>
        public static string ViewSuspensionOrder {
            get {
                return ResourceManager.GetString("ViewSuspensionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Account Service.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to process already saved data?.
        /// </summary>
        public static string WantToProcessAlreadySavedData {
            get {
                return ResourceManager.GetString("WantToProcessAlreadySavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload new file?.
        /// </summary>
        public static string WantToUploadNewFile {
            get {
                return ResourceManager.GetString("WantToUploadNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Consumption.
        /// </summary>
        public static string WaterConsumption {
            get {
                return ResourceManager.GetString("WaterConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water consumption must be at least 1..
        /// </summary>
        public static string WaterConsumptionErrMsg {
            get {
                return ResourceManager.GetString("WaterConsumptionErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        public static string WhatWouldYouLikeToDo {
            get {
                return ResourceManager.GetString("WhatWouldYouLikeToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width should be greater than zero..
        /// </summary>
        public static string WidthRequiredMessage {
            get {
                return ResourceManager.GetString("WidthRequiredMessage", resourceCulture);
            }
        }
    }
}
