//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Case {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Case() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.Case", typeof(Case).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Legal Case.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By User.
        /// </summary>
        public static string ByUser {
            get {
                return ResourceManager.GetString("ByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The following files have been upload:{0}. Review Attachment section in case..
        /// </summary>
        public static string CaseExtraComment {
            get {
                return ResourceManager.GetString("CaseExtraComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case ID.
        /// </summary>
        public static string CaseID {
            get {
                return ResourceManager.GetString("CaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases Quantity by Status.
        /// </summary>
        public static string CasesCountbyStatus {
            get {
                return ResourceManager.GetString("CasesCountbyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases Money by Status.
        /// </summary>
        public static string CasesMoneybyStatus {
            get {
                return ResourceManager.GetString("CasesMoneybyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIM Information.
        /// </summary>
        public static string CRIMInformation {
            get {
                return ResourceManager.GetString("CRIMInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIM Reference Code.
        /// </summary>
        public static string CRIMReferenceCode {
            get {
                return ResourceManager.GetString("CRIMReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIM Reference Date.
        /// </summary>
        public static string CRIMReferenceDate {
            get {
                return ResourceManager.GetString("CRIMReferenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        public static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatary.
        /// </summary>
        public static string Destinatary {
            get {
                return ResourceManager.GetString("Destinatary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Activity.
        /// </summary>
        public static string EditActivity {
            get {
                return ResourceManager.GetString("EditActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Legal Case.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Amount.
        /// </summary>
        public static string EstimateAmount {
            get {
                return ResourceManager.GetString("EstimateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heir Information.
        /// </summary>
        public static string HeirInformation {
            get {
                return ResourceManager.GetString("HeirInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License, IVU and Services.
        /// </summary>
        public static string License_IVU_Services {
            get {
                return ResourceManager.GetString("License_IVU_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MeetingType {
            get {
                return ResourceManager.GetString("MeetingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Activity.
        /// </summary>
        public static string NewActivity {
            get {
                return ResourceManager.GetString("NewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Attachment.
        /// </summary>
        public static string NewAttachment {
            get {
                return ResourceManager.GetString("NewAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New History.
        /// </summary>
        public static string NewHistory {
            get {
                return ResourceManager.GetString("NewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Print Letter.
        /// </summary>
        public static string NewPrintLetter {
            get {
                return ResourceManager.GetString("NewPrintLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        public static string OutputFormat {
            get {
                return ResourceManager.GetString("OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Center.
        /// </summary>
        public static string PrintCenterList {
            get {
                return ResourceManager.GetString("PrintCenterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Letter.
        /// </summary>
        public static string PrintLetter {
            get {
                return ResourceManager.GetString("PrintLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouce Information.
        /// </summary>
        public static string SpouceInformation {
            get {
                return ResourceManager.GetString("SpouceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Activity.
        /// </summary>
        public static string ViewActivity {
            get {
                return ResourceManager.GetString("ViewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Legal Case.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        public static string WorkflowStatus {
            get {
                return ResourceManager.GetString("WorkflowStatus", resourceCulture);
            }
        }
    }
}
