//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.Chat", typeof(Chat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent had left chat please wait untill another agent accepts your request or click refresh button to check the agent availability..
        /// </summary>
        public static string AgentOfflineMessage {
            get {
                return ResourceManager.GetString("AgentOfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is online..
        /// </summary>
        public static string AgentOnlineMessage {
            get {
                return ResourceManager.GetString("AgentOnlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ticket.
        /// </summary>
        public static string BTNCreateTicket {
            get {
                return ResourceManager.GetString("BTNCreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a better experience please use another browser.
        /// </summary>
        public static string IEChatMessage {
            get {
                return ResourceManager.GetString("IEChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Chat.
        /// </summary>
        public static string LiveChat {
            get {
                return ResourceManager.GetString("LiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise a Service Request.
        /// </summary>
        public static string MsgRaiseServiceRequest {
            get {
                return ResourceManager.GetString("MsgRaiseServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise a service request to ask your query. We will be happy to help you..
        /// </summary>
        public static string MsgRaiseServiceRequestDesc {
            get {
                return ResourceManager.GetString("MsgRaiseServiceRequestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayTitle {
            get {
                return ResourceManager.GetString("TodayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been transfer to Chat with .
        /// </summary>
        public static string TransferMessage {
            get {
                return ResourceManager.GetString("TransferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to chat, Please wait while one of our online agent connects with you..
        /// </summary>
        public static string WelComeChatMessage {
            get {
                return ResourceManager.GetString("WelComeChatMessage", resourceCulture);
            }
        }
    }
}
