//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class COLClosing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COLClosing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.COLClosing", typeof(COLClosing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Register.
        /// </summary>
        public static string CloseEntry {
            get {
                return ResourceManager.GetString("CloseEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposited.
        /// </summary>
        public static string Deposited {
            get {
                return ResourceManager.GetString("Deposited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Cash Register.
        /// </summary>
        public static string ListCloseEntryDay {
            get {
                return ResourceManager.GetString("ListCloseEntryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Cash Register.
        /// </summary>
        public static string NewCloseEntryDay {
            get {
                return ResourceManager.GetString("NewCloseEntryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Amount.
        /// </summary>
        public static string ReceiptAmount {
            get {
                return ResourceManager.GetString("ReceiptAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment Receipt.
        /// </summary>
        public static string TotalPaymentReceipt {
            get {
                return ResourceManager.GetString("TotalPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment Receipts.
        /// </summary>
        public static string TotalPaymentReceipts {
            get {
                return ResourceManager.GetString("TotalPaymentReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing amount should be greater than zero..
        /// </summary>
        public static string ValClosingAmount {
            get {
                return ResourceManager.GetString("ValClosingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select minimum one receipt..
        /// </summary>
        public static string ValMinOneReceipt {
            get {
                return ResourceManager.GetString("ValMinOneReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Daily Cash Register.
        /// </summary>
        public static string ViewCloseEntryDay {
            get {
                return ResourceManager.GetString("ViewCloseEntryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Entry.
        /// </summary>
        public static string VoidEntry {
            get {
                return ResourceManager.GetString("VoidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash register voided successfully..
        /// </summary>
        public static string VoidSuccessMsg {
            get {
                return ResourceManager.GetString("VoidSuccessMsg", resourceCulture);
            }
        }
    }
}
