//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class COLDeposit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COLDeposit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.COLDeposit", typeof(COLDeposit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Amount.
        /// </summary>
        public static string ClosingAmount {
            get {
                return ResourceManager.GetString("ClosingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closings.
        /// </summary>
        public static string ClosingCount {
            get {
                return ResourceManager.GetString("ClosingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Description.
        /// </summary>
        public static string ClosingDescription {
            get {
                return ResourceManager.GetString("ClosingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Entries.
        /// </summary>
        public static string ListDepositEntry {
            get {
                return ResourceManager.GetString("ListDepositEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deposit Entry.
        /// </summary>
        public static string NewDepositEntry {
            get {
                return ResourceManager.GetString("NewDepositEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Receipts.
        /// </summary>
        public static string PaymentReceipts {
            get {
                return ResourceManager.GetString("PaymentReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Closing Entry.
        /// </summary>
        public static string TotalClosingEntry {
            get {
                return ResourceManager.GetString("TotalClosingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit amount should be greater than zero..
        /// </summary>
        public static string ValDepositAmount {
            get {
                return ResourceManager.GetString("ValDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select minimum one entry..
        /// </summary>
        public static string ValMinOneCloseEntry {
            get {
                return ResourceManager.GetString("ValMinOneCloseEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Deposit Entry.
        /// </summary>
        public static string ViewDepositEntry {
            get {
                return ResourceManager.GetString("ViewDepositEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Closed Entry.
        /// </summary>
        public static string VoidClosedEntry {
            get {
                return ResourceManager.GetString("VoidClosedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Deposit Entry.
        /// </summary>
        public static string VoidDepositEntry {
            get {
                return ResourceManager.GetString("VoidDepositEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit entry voided successfully..
        /// </summary>
        public static string VoidSuccessMsg {
            get {
                return ResourceManager.GetString("VoidSuccessMsg", resourceCulture);
            }
        }
    }
}
