//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class COLInvoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COLInvoice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.COLInvoice", typeof(COLInvoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Invoice.
        /// </summary>
        public static string EditInvoice {
            get {
                return ResourceManager.GetString("EditInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select different Grants for each row..
        /// </summary>
        public static string GrantServiceCompareMsg {
            get {
                return ResourceManager.GetString("GrantServiceCompareMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Invoice Number..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string ListInvoice {
            get {
                return ResourceManager.GetString("ListInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string NewInvoice {
            get {
                return ResourceManager.GetString("NewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Other Service.
        /// </summary>
        public static string NewOtherService {
            get {
                return ResourceManager.GetString("NewOtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice cannot be created for two different types..
        /// </summary>
        public static string OtherServiceCompareMsg {
            get {
                return ResourceManager.GetString("OtherServiceCompareMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Invoice.
        /// </summary>
        public static string PayInvoice {
            get {
                return ResourceManager.GetString("PayInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment already processed for invoice..
        /// </summary>
        public static string PaymentReceiptExistErrMsg {
            get {
                return ResourceManager.GetString("PaymentReceiptExistErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Invoice.
        /// </summary>
        public static string PosInvoice {
            get {
                return ResourceManager.GetString("PosInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoice.
        /// </summary>
        public static string PrintInvoice {
            get {
                return ResourceManager.GetString("PrintInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select different service for each row..
        /// </summary>
        public static string ServiceCompareMsg {
            get {
                return ResourceManager.GetString("ServiceCompareMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Invoice can not be edited..
        /// </summary>
        public static string ServiceInvoiceUpdateErrMsg {
            get {
                return ResourceManager.GetString("ServiceInvoiceUpdateErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one line-item allowed for type other service.
        /// </summary>
        public static string ServiceTypeMsg {
            get {
                return ResourceManager.GetString("ServiceTypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total should be greater than zero..
        /// </summary>
        public static string TotalValidationMsg {
            get {
                return ResourceManager.GetString("TotalValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Invoice.
        /// </summary>
        public static string UpdateInvoice {
            get {
                return ResourceManager.GetString("UpdateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Invoice.
        /// </summary>
        public static string ViewInvoice {
            get {
                return ResourceManager.GetString("ViewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided invoice can not be edited..
        /// </summary>
        public static string VoidedInvoiceUpdateErrorMsg {
            get {
                return ResourceManager.GetString("VoidedInvoiceUpdateErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Invoice.
        /// </summary>
        public static string VoidInvoice {
            get {
                return ResourceManager.GetString("VoidInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice voided successfully!.
        /// </summary>
        public static string VoidSuccessMsg {
            get {
                return ResourceManager.GetString("VoidSuccessMsg", resourceCulture);
            }
        }
    }
}
