//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Company {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Company() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.Company", typeof(Company).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        public static string AddressDetail {
            get {
                return ResourceManager.GetString("AddressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code (MUNITAX).
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string CompanyConfigurationTitle {
            get {
                return ResourceManager.GetString("CompanyConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string CompanyConfirmationTitle {
            get {
                return ResourceManager.GetString("CompanyConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string CompanyDetailsTitle {
            get {
                return ResourceManager.GetString("CompanyDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string CompanyModulesTitle {
            get {
                return ResourceManager.GetString("CompanyModulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                    Company you are trying to access is not configured.
        ///                &lt;/p&gt;
        ///                &lt;p&gt;Please, contact your company owner.&lt;/p&gt;.
        /// </summary>
        public static string CompanyNotConfiguredMessage {
            get {
                return ResourceManager.GetString("CompanyNotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not configured.
        /// </summary>
        public static string CompanyNotConfiguredTitle {
            get {
                return ResourceManager.GetString("CompanyNotConfiguredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Size.
        /// </summary>
        public static string CompanySize {
            get {
                return ResourceManager.GetString("CompanySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company has been saved successfully!.
        /// </summary>
        public static string CompanySucessMessage {
            get {
                return ResourceManager.GetString("CompanySucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company code already exists!.
        /// </summary>
        public static string DuplicateCompanyCode {
            get {
                return ResourceManager.GetString("DuplicateCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LegalName {
            get {
                return ResourceManager.GetString("LegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string NavEditTitle {
            get {
                return ResourceManager.GetString("NavEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Decimal Points Allowed.
        /// </summary>
        public static string NoOfDecimalPointsAllowed {
            get {
                return ResourceManager.GetString("NoOfDecimalPointsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 0 to 5 decimal points are allowed..
        /// </summary>
        public static string NoOfDecimalPointsRangeMessage {
            get {
                return ResourceManager.GetString("NoOfDecimalPointsRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies, arcu sit amet tempus semper, orci ante tempor sapien, nec condimentum ipsum urna non sapien. Donec ut placerat elit. Donec varius lacus vitae vehicula vestibulum. In eu fringilla sem. Duis lacinia ligula ut scelerisque placerat. Donec euismod magna ac ligula laoreet, quis cursus libero sodales. Sed interdum, erat non efficitur sagittis, odio lectus tempor mauris, in tincidunt velit metus non dolor. Sed eget lorem ultrices, interdum nulla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree the terms and policy..
        /// </summary>
        public static string TermsAndPolicyMessage {
            get {
                return ResourceManager.GetString("TermsAndPolicyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account Receivable Journal.
        /// </summary>
        public static string UseAccountReceivableJournal {
            get {
                return ResourceManager.GetString("UseAccountReceivableJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Leap Year.
        /// </summary>
        public static string UseLeapYear {
            get {
                return ResourceManager.GetString("UseLeapYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
