//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.PaymentPlan", typeof(PaymentPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Payment Plan.
        /// </summary>
        public static string EditServicePaymentPlan {
            get {
                return ResourceManager.GetString("EditServicePaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective To should be greater than Effective From..
        /// </summary>
        public static string EffectiveToShouldBeGreaterThanEffectiveFromMsg {
            get {
                return ResourceManager.GetString("EffectiveToShouldBeGreaterThanEffectiveFromMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalment.
        /// </summary>
        public static string Instalment {
            get {
                return ResourceManager.GetString("Instalment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Interests.
        /// </summary>
        public static string InterestPerMonth {
            get {
                return ResourceManager.GetString("InterestPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests for Late Payments.
        /// </summary>
        public static string InterestsForLatePayments {
            get {
                return ResourceManager.GetString("InterestsForLatePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Plan.
        /// </summary>
        public static string InvalidPaymentPlan {
            get {
                return ResourceManager.GetString("InvalidPaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Payment Interest.
        /// </summary>
        public static string LatePaymentInterest {
            get {
                return ResourceManager.GetString("LatePaymentInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Service Payment Plan.
        /// </summary>
        public static string ListServicePaymentPlan {
            get {
                return ResourceManager.GetString("ListServicePaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Interest.
        /// </summary>
        public static string MonthlyInterest {
            get {
                return ResourceManager.GetString("MonthlyInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be equal or greater than 1..
        /// </summary>
        public static string MustBeEqualOrGreaterThan3Msg {
            get {
                return ResourceManager.GetString("MustBeEqualOrGreaterThan3Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service Payment Plan.
        /// </summary>
        public static string NewServicePaymentPlan {
            get {
                return ResourceManager.GetString("NewServicePaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Months.
        /// </summary>
        public static string NoOfMonths {
            get {
                return ResourceManager.GetString("NoOfMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Service Payment Plan.
        /// </summary>
        public static string ViewServicePaymentPlan {
            get {
                return ResourceManager.GetString("ViewServicePaymentPlan", resourceCulture);
            }
        }
    }
}
