//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceCollectionTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceCollectionTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.ServiceCollectionTemplate", typeof(ServiceCollectionTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection Template.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbook.
        /// </summary>
        public static string Checkbook {
            get {
                return ResourceManager.GetString("Checkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Account.
        /// </summary>
        public static string CreditAccount {
            get {
                return ResourceManager.GetString("CreditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate entry found..
        /// </summary>
        public static string DuplicateEntryMessage {
            get {
                return ResourceManager.GetString("DuplicateEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Collection Template.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Collection Template Number..
        /// </summary>
        public static string InvalidTemplateNumber {
            get {
                return ResourceManager.GetString("InvalidTemplateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Collection Template.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbook is not available in selected grant..
        /// </summary>
        public static string NotAvailableCheckbook {
            get {
                return ResourceManager.GetString("NotAvailableCheckbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Value should be 100%..
        /// </summary>
        public static string PercentageNotValidMessage {
            get {
                return ResourceManager.GetString("PercentageNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivable Account.
        /// </summary>
        public static string ReceivableAccount {
            get {
                return ResourceManager.GetString("ReceivableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Grant.
        /// </summary>
        public static string RemoveGrant {
            get {
                return ResourceManager.GetString("RemoveGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Account.
        /// </summary>
        public static string RevenueAccount {
            get {
                return ResourceManager.GetString("RevenueAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of Collection must be the same for each year..
        /// </summary>
        public static string ValCollectionTypeSameForEachYear {
            get {
                return ResourceManager.GetString("ValCollectionTypeSameForEachYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun value should be 100..
        /// </summary>
        public static string ValMaxPercentageValueMessage {
            get {
                return ResourceManager.GetString("ValMaxPercentageValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal collection should be allocated for each year..
        /// </summary>
        public static string ValMinTemplateItem {
            get {
                return ResourceManager.GetString("ValMinTemplateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Collection Template.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Allocation.
        /// </summary>
        public static string YearAllocation {
            get {
                return ResourceManager.GetString("YearAllocation", resourceCulture);
            }
        }
    }
}
