//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Transfer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transfer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.Transfer", typeof(Transfer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Transfer.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Owner.
        /// </summary>
        public static string CurrentOwner {
            get {
                return ResourceManager.GetString("CurrentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        public static string FromAccountName {
            get {
                return ResourceManager.GetString("FromAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Merge.
        /// </summary>
        public static string NewMerge {
            get {
                return ResourceManager.GetString("NewMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Right.
        /// </summary>
        public static string NewRightMerge {
            get {
                return ResourceManager.GetString("NewRightMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Right.
        /// </summary>
        public static string NewRightSplit {
            get {
                return ResourceManager.GetString("NewRightSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Split.
        /// </summary>
        public static string NewSplit {
            get {
                return ResourceManager.GetString("NewSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Transfer.
        /// </summary>
        public static string NewTransfer {
            get {
                return ResourceManager.GetString("NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Owner.
        /// </summary>
        public static string PreviousOwner {
            get {
                return ResourceManager.GetString("PreviousOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cedula has services which don&apos;t have Right information associated..
        /// </summary>
        public static string TaxNumberAssociatedWithServicesHasNoRight {
            get {
                return ResourceManager.GetString("TaxNumberAssociatedWithServicesHasNoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string ToAccountName {
            get {
                return ResourceManager.GetString("ToAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Date.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Transfer.
        /// </summary>
        public static string TransferList {
            get {
                return ResourceManager.GetString("TransferList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Type.
        /// </summary>
        public static string TransferType {
            get {
                return ResourceManager.GetString("TransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select the same account to make the transfer. Please select a different one..
        /// </summary>
        public static string ValAccountCompare {
            get {
                return ResourceManager.GetString("ValAccountCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one for service.
        /// </summary>
        public static string ValRequireService {
            get {
                return ResourceManager.GetString("ValRequireService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Merge.
        /// </summary>
        public static string ViewMerge {
            get {
                return ResourceManager.GetString("ViewMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Transfer.
        /// </summary>
        public static string ViewServicTransfer {
            get {
                return ResourceManager.GetString("ViewServicTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Split.
        /// </summary>
        public static string ViewSplit {
            get {
                return ResourceManager.GetString("ViewSplit", resourceCulture);
            }
        }
    }
}
