//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtSolutions.MUN.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Workflow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workflow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtSolutions.MUN.Web.Resources.Workflow", typeof(Workflow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workflow.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Delete.
        /// </summary>
        public static string AllowDelete {
            get {
                return ResourceManager.GetString("AllowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Edit.
        /// </summary>
        public static string AllowEdit {
            get {
                return ResourceManager.GetString("AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to.
        /// </summary>
        public static string Assignto {
            get {
                return ResourceManager.GetString("Assignto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Status.
        /// </summary>
        public static string CreateStatus {
            get {
                return ResourceManager.GetString("CreateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Workflow.
        /// </summary>
        public static string CreateWorkflow {
            get {
                return ResourceManager.GetString("CreateWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type .
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reason.
        /// </summary>
        public static string EditReason {
            get {
                return ResourceManager.GetString("EditReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Status.
        /// </summary>
        public static string EditStatus {
            get {
                return ResourceManager.GetString("EditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Workflow.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Status.
        /// </summary>
        public static string FromStatus {
            get {
                return ResourceManager.GetString("FromStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Status.
        /// </summary>
        public static string InitialStatus {
            get {
                return ResourceManager.GetString("InitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Full.
        /// </summary>
        public static string IsFull {
            get {
                return ResourceManager.GetString("IsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Partial.
        /// </summary>
        public static string IsPartial {
            get {
                return ResourceManager.GetString("IsPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Form.
        /// </summary>
        public static string ListForm {
            get {
                return ResourceManager.GetString("ListForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Group.
        /// </summary>
        public static string ListGroup {
            get {
                return ResourceManager.GetString("ListGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Reason.
        /// </summary>
        public static string ListReason {
            get {
                return ResourceManager.GetString("ListReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Workflow.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reason.
        /// </summary>
        public static string NewReason {
            get {
                return ResourceManager.GetString("NewReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sequence.
        /// </summary>
        public static string NewSequence {
            get {
                return ResourceManager.GetString("NewSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status.
        /// </summary>
        public static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workflow.
        /// </summary>
        public static string NewTitle {
            get {
                return ResourceManager.GetString("NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Sequence.
        /// </summary>
        public static string StatusSequence {
            get {
                return ResourceManager.GetString("StatusSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast add one status in this Workflow..
        /// </summary>
        public static string StatusValidataion {
            get {
                return ResourceManager.GetString("StatusValidataion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Status.
        /// </summary>
        public static string TargetStatus {
            get {
                return ResourceManager.GetString("TargetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Status.
        /// </summary>
        public static string ToStatus {
            get {
                return ResourceManager.GetString("ToStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Popup.
        /// </summary>
        public static string UsePopup {
            get {
                return ResourceManager.GetString("UsePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Group.
        /// </summary>
        public static string ViewGroup {
            get {
                return ResourceManager.GetString("ViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reason.
        /// </summary>
        public static string ViewReason {
            get {
                return ResourceManager.GetString("ViewReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Status.
        /// </summary>
        public static string ViewStatus {
            get {
                return ResourceManager.GetString("ViewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Workflow.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Diagram.
        /// </summary>
        public static string WorkflowDiagram {
            get {
                return ResourceManager.GetString("WorkflowDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Editor.
        /// </summary>
        public static string WorkflowEditor {
            get {
                return ResourceManager.GetString("WorkflowEditor", resourceCulture);
            }
        }
    }
}
